"use client";

import { useMemo, useRef } from "react";
import * as THREE from "three";
import { FrameDriver, fitVisibility, type ViewRef } from "@/components/v4-1/mapScene";
import { INDIA_OUTLINE } from "@/lib/mapData/india";
import { WORLD_LAND } from "@/lib/mapData/world";

/**
 * The real ground the version 4.2 world stands on: India's actual coastline
 * for the close-in stages, and the whole world's continents for the pulled-
 * back one, so guests really are coming from where they say they are. Both
 * are always in the scene; which one reads as "the map" is just a matter of
 * opacity, crossfaded by how far the camera has pulled back.
 */

/** Lon/lat rings, [exterior, ...holes] per polygon, as generated by scripts/build-map-data.mjs. */
type Polygons = [number, number][][][];

/** Builds one merged fill (for every polygon, holes cut out) and one merged coastline stroke. */
function buildLand(polygons: Polygons, project: (lon: number, lat: number) => [number, number]) {
  const shapes = polygons.map(([exterior, ...holes]) => {
    const shape = new THREE.Shape(exterior.map(([lon, lat]) => new THREE.Vector2(...project(lon, lat))));
    holes.forEach((hole) => {
      shape.holes.push(new THREE.Path(hole.map(([lon, lat]) => new THREE.Vector2(...project(lon, lat)))));
    });
    return shape;
  });
  const fill = new THREE.ShapeGeometry(shapes);

  // Every ring (exterior and holes) drawn as one batch of disjoint segments — one draw call
  // rather than one Line per country.
  const strokePoints: number[] = [];
  polygons.forEach((rings) =>
    rings.forEach((ring) => {
      for (let i = 0; i < ring.length; i += 1) {
        const [x, y] = project(...ring[i]);
        const [nx, ny] = project(...ring[(i + 1) % ring.length]);
        strokePoints.push(x, 0, y, nx, 0, ny);
      }
    }),
  );
  const stroke = new THREE.BufferGeometry();
  stroke.setAttribute("position", new THREE.Float32BufferAttribute(strokePoints, 3));

  return { fill, stroke };
}

export interface LandmassProps {
  view: ViewRef;
  /** Where 0° longitude, 0° latitude falls, so the shapes line up with the routes and pins. */
  gridOrigin: { x: number; z: number };
  land: string;
  ocean: string;
  coastline: string;
  /** Fit beyond which India's detailed outline gives way to the whole-world one. */
  crossfadeAt?: number;
}

export default function Landmass({ view, gridOrigin, land, ocean, coastline, crossfadeAt = 150 }: LandmassProps) {
  const originLon = -gridOrigin.x;
  const originLat = gridOrigin.z;
  // Same convention as `at()` elsewhere (x = lon − origin, z = origin − lat), then laid flat:
  // ShapeGeometry builds in its local XY, and rotating the mesh +90° about X sends that Y to
  // world Z untouched — flip the sign here instead and the map comes out mirrored.
  const project = useMemo(
    () =>
      (lon: number, lat: number): [number, number] => [lon - originLon, originLat - lat],
    [originLon, originLat],
  );

  const india = useMemo(() => buildLand(INDIA_OUTLINE, project), [project]);
  const world = useMemo(() => buildLand(WORLD_LAND, project), [project]);

  const indiaFillRef = useRef<THREE.MeshStandardMaterial>(null);
  const indiaStrokeRef = useRef<THREE.LineBasicMaterial>(null);
  const worldFillRef = useRef<THREE.MeshStandardMaterial>(null);
  const worldStrokeRef = useRef<THREE.LineBasicMaterial>(null);

  const run = () => {
    const indiaOpacity = fitVisibility(view.current.fit, crossfadeAt);
    const worldOpacity = 1 - indiaOpacity;
    if (indiaFillRef.current) indiaFillRef.current.opacity = indiaOpacity;
    if (indiaStrokeRef.current) indiaStrokeRef.current.opacity = indiaOpacity;
    if (worldFillRef.current) worldFillRef.current.opacity = worldOpacity;
    if (worldStrokeRef.current) worldStrokeRef.current.opacity = worldOpacity;
  };

  return (
    <>
      <FrameDriver run={run} />
      {/* The sea: everywhere that isn't land, so the coastline actually reads as one */}
      <mesh rotation={[-Math.PI / 2, 0, 0]} position={[0, -0.05, 0]}>
        <planeGeometry args={[6000, 6000]} />
        <meshStandardMaterial color={ocean} roughness={1} metalness={0} />
      </mesh>

      <mesh geometry={india.fill} rotation={[Math.PI / 2, 0, 0]}>
        <meshStandardMaterial
          ref={indiaFillRef}
          color={land}
          roughness={0.95}
          transparent
          side={THREE.DoubleSide}
        />
      </mesh>
      <lineSegments geometry={india.stroke}>
        <lineBasicMaterial ref={indiaStrokeRef} color={coastline} transparent />
      </lineSegments>

      <mesh geometry={world.fill} rotation={[Math.PI / 2, 0, 0]} position={[0, -0.02, 0]}>
        <meshStandardMaterial
          ref={worldFillRef}
          color={land}
          roughness={0.95}
          transparent
          side={THREE.DoubleSide}
        />
      </mesh>
      <lineSegments geometry={world.stroke} position={[0, -0.02, 0]}>
        <lineBasicMaterial ref={worldStrokeRef} color={coastline} transparent />
      </lineSegments>
    </>
  );
}
